/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get games
         * @description Get all games that are available to the provided API key.
         */
        get: operations["getGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/games/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get game
         * @description Get a single game. A private game is only accessible by its respective API key.
         */
        get: operations["getGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/games/{gameId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get versions
         * @description Get all available versions for each known version type of the specified game. A private game is only accessible to its respective API key.
         */
        get: operations["getVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/games/{gameId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get versions
         * @description Get all available versions for each known version type of the specified game. A private game is only accessible to its respective API key.
         */
        get: operations["getVersionsV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/games/{gameId}/version-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get version types
         * @description Get all available version types of the specified game.
         *     A private game is only accessible to its respective API key.
         *     Currently, when creating games via the CurseForge Core Console, you are limited to a single game version type. This means that this endpoint is probably not useful in most cases and is relevant mostly when handling existing games that have multiple game versions such as World of Warcraft and Minecraft (e.g. 517 for wow_retail).
         */
        get: operations["getVersionTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get categories
         * @description Get all available classes and categories of the specified game. Specify a game id for a list of all game categories, or a class id for a list of categories under that class.
         */
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mods/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all mods that match the search criteria.
         * @description Get all mods that match the search criteria.
         */
        get: operations["searchMods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mods/{modId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single mod.
         * @description Get a single mod.
         */
        get: operations["getMod"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a list of mods.
         * @description Get a list of mods.
         */
        post: operations["getMods"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mods/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get featured mods.
         * @description Get a list of featured, popular and recently updated mods.
         */
        post: operations["getFeaturedMods"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mods/{modId}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod description.
         * @description Get the full description of a mod in HTML format.
         */
        get: operations["getModDescription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mods/{modId}/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file.
         * @description Get a single file of the specified mod.
         */
        get: operations["getModFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mods/{modId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod files.
         * @description Get all files of the specified mod.
         */
        get: operations["getModFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mods/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get files
         * @description Get a list of files.
         */
        post: operations["getFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mods/{modId}/files/{fileId}/changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file changelog
         * @description Get the changelog of a file in HTML format.
         */
        get: operations["getModFileChangelog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mods/{modId}/files/{fileId}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mod File Download URL
         * @description Get a download url for a specific file.
         */
        get: operations["getModFileDownloadURL"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fingerprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Fingerprints Matches
         * @description Get mod files that match a list of fingerprints (murmur2 hashes with seed 1).
         */
        post: operations["getFingerprintMatches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fingerprints/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Fingerprints Matches
         * @description Get mod files that match a list of fingerprints.
         */
        post: operations["getFingerprintMatchesByGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fingerprints/fuzzy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Fingerprints Fuzzy Matches
         * @description Get mod files that match a list of fingerprints using fuzzy matching.
         */
        post: operations["getFingerprintFuzzyMatches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fingerprints/fuzzy/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Fingerprints Fuzzy Matches
         * @description Get mod files that match a list of fingerprints using fuzzy matching.
         */
        post: operations["getFingerprintFuzzyMatchesByGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/minecraft/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Minecraft Versions
         * @description Get Minecraft Versions
         */
        get: operations["getMinecraftVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/minecraft/version/{gameVersionString}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Specific Minecraft Version
         * @description Get Specific Minecraft Version
         */
        get: operations["getSpecificMinecraftVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/minecraft/modloader": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Minecraft ModLoaders
         * @description Get Minecraft ModLoaders
         */
        get: operations["getMinecraftModLoaders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/minecraft/modloader/{modLoaderName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Specific Minecraft ModLoader
         * @description Get Specific Minecraft ModLoader
         */
        get: operations["getSpecificMinecraftModLoader"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /**
         * @description * 1 = Bisect
         *
         *     Note: Bisect appears to have both id 1 and 2 for some reason. This is not documented in the official API spec
         *     The official spec also does not mention 0 which appears to be the default for projects that do not use the
         *     affiliate program.
         * @enum {integer}
         */
        AffiliationServiceType: AffiliationServiceType;
        ApiResponseOfListOfMinecraftGameVersion: {
            data: components["schemas"]["MinecraftGameVersion"][];
        };
        ApiResponseOfListOfMinecraftModLoaderIndex: {
            data: components["schemas"]["MinecraftModLoaderIndex"][];
        };
        ApiResponseOfMinecraftGameVersion: {
            data: components["schemas"]["MinecraftGameVersion"];
        };
        ApiResponseOfMinecraftModLoaderVersion: {
            data: components["schemas"]["MinecraftModLoaderVersion"];
        };
        Category: {
            /**
             * Format: int32
             * @description The category id
             */
            id: number;
            /**
             * Format: int32
             * @description The game id related to the category
             */
            gameId: number;
            /** @description Category name */
            name: string;
            /** @description The category slug as it appear in the URL */
            slug: string;
            /**
             * Format: uri
             * @description The category URL
             */
            url: string;
            /**
             * Format: uri
             * @description URL for the category icon
             */
            iconUrl: string;
            /**
             * Format: date-time
             * @description Last modified date of the category
             */
            dateModified: string;
            /** @description A top level category for other categories */
            isClass: boolean | null;
            /**
             * Format: int32
             * @description The class id of the category, meaning - the class of which this category is under
             */
            classId: number | null;
            /**
             * Format: int32
             * @description The parent category for this category
             */
            parentCategoryId: number | null;
            /**
             * Format: int32
             * @description The display index for this category
             */
            displayIndex: number | null;
        };
        /**
         * @description CoreApiStatus
         *     Possible enum values:
         *      * 1 = Private
         *      * 2 = Public
         * @enum {integer}
         */
        CoreApiStatus: CoreApiStatus;
        /**
         * @description CoreStatus
         *     Possible enum values:
         *      * 1 = Draft
         *      * 2 = Test
         *      * 3 = PendingReview
         *      * 4 = Rejected
         *      * 5 = Approved
         *      * 6 = Live
         * @enum {integer}
         */
        CoreStatus: CoreStatus;
        FeaturedModsResponse: {
            featured: components["schemas"]["Mod"][];
            popular: components["schemas"]["Mod"][];
            recentlyUpdated: components["schemas"]["Mod"][];
        };
        File: {
            /**
             * Format: int32
             * @description The file id
             */
            id: number;
            /**
             * Format: int32
             * @description The game id related to the mod that this file belongs to
             */
            gameId: number;
            /**
             * Format: int32
             * @description The mod id
             */
            modId: number;
            /** @description Whether the file is available to download */
            isAvailable: boolean;
            /** @description Display name of the file */
            displayName: string;
            /** @description Exact file name */
            fileName: string;
            releaseType: components["schemas"]["FileReleaseType"];
            fileStatus: components["schemas"]["FileStatus"];
            /** @description The file hash (i.e. md5 or sha1) */
            hashes: components["schemas"]["FileHash"][];
            /**
             * Format: date-time
             * @description The file timestamp
             */
            fileDate: string;
            /**
             * Format: int64
             * @description The file length in bytes
             */
            fileLength: number;
            /**
             * Format: int64
             * @description The file's size on disk
             */
            fileSizeOnDisk: number | null;
            /**
             * Format: int64
             * @description The number of downloads for the file
             */
            downloadCount: number;
            /** Format: uri */
            downloadUrl: string | null;
            /** @description List of game versions this file is relevant for */
            gameVersions: string[];
            /** @description Metadata used for sorting by game versions */
            sortableGameVersions: components["schemas"]["SortableGameVersion"][];
            /** @description List of dependencies files */
            dependencies: components["schemas"]["FileDependency"][];
            exposeAsAlternative: boolean | null;
            /** Format: int32 */
            parentProjectFileId: number | null;
            /** Format: int32 */
            alternateFileId: number | null;
            isServerPack: boolean | null;
            /** Format: int32 */
            serverPackFileId: number | null;
            isEarlyAccessContent: boolean | null;
            /** Format: date-time */
            earlyAccessEndDate: string | null;
            /** Format: int64 */
            fileFingerprint: number;
            modules: components["schemas"]["FileModule"][];
        };
        FileDependency: {
            /** Format: int32 */
            modId: number;
            relationType: components["schemas"]["FileRelationType"];
        };
        FileHash: {
            value: string;
            algo: components["schemas"]["HashAlgo"];
        };
        FileIndex: {
            gameVersion: string;
            /** Format: int32 */
            fileId: number;
            filename: string;
            releaseType: components["schemas"]["FileReleaseType"];
            /** Format: int32 */
            gameVersionTypeId: number | null;
            modLoader: components["schemas"]["ModLoaderType"];
        };
        FileModule: {
            name: string;
            /** Format: int64 */
            fingerprint: number;
        };
        /**
         * @description Possible enum values:
         *      * 1 = EmbeddedLibrary
         *      * 2 = OptionalDependency
         *      * 3 = RequiredDependency
         *      * 4 = Tool
         *      * 5 = Incompatible
         *      * 6 = Include
         * @enum {integer}
         */
        FileRelationType: FileRelationType;
        /**
         * @description Possible enum values:
         *      * 1 = Release
         *      * 2 = Beta
         *      * 3 = Alpha
         * @enum {integer}
         */
        FileReleaseType: FileReleaseType;
        /**
         * @description Status of the file
         *     Possible enum values:
         *      * 1 = Processing
         *      * 2 = ChangesRequired
         *      * 3 = UnderReview
         *      * 4 = Approved
         *      * 5 = Rejected
         *      * 6 = MalwareDetected
         *      * 7 = Deleted
         *      * 8 = Archived
         *      * 9 = Testing
         *      * 10 = Released
         *      * 11 = ReadyForReview
         *      * 12 = Deprecated
         *      * 13 = Baking
         *      * 14 = AwaitingPublishing
         *      * 15 = FailedPublishing
         *      * 16 = Cooking
         *      * 17 = Cooked
         *      * 18 = UnderManualReview
         *      * 19 = ScanningForMalware
         *      * 20 = ProcessingFile
         *      * 21 = PendingRelease
         *      * 22 = ReadyForCooking
         *      * 23 = PostProcessing
         * @enum {integer}
         */
        FileStatus: FileStatus;
        FingerprintFuzzyMatch: {
            /** Format: int32 */
            id: number;
            file: components["schemas"]["File"];
            latestFiles: components["schemas"]["File"][];
            fingerprints: number[];
        };
        FingerprintFuzzyMatchResult: {
            fuzzyMatches: components["schemas"]["FingerprintFuzzyMatch"][];
        };
        FingerprintMatch: {
            /** Format: int32 */
            id: number;
            file: components["schemas"]["File"];
            latestFiles: components["schemas"]["File"][];
        };
        FingerprintMatchesResult: {
            isCacheBuilt: boolean;
            exactMatches: components["schemas"]["FingerprintMatch"][];
            exactFingerprints: number[];
            partialMatches: components["schemas"]["FingerprintMatch"][];
            partialMatchFingerprints: {
                [key: string]: number[];
            };
            installedFingerprints: number[];
            unmatchedFingerprints: number[];
        };
        FolderFingerprint: {
            foldername: string;
            fingerprints: number[];
        };
        Game: {
            /** Format: int32 */
            id: number;
            name: string;
            slug: string;
            /** Format: date-time */
            dateModified: string;
            assets: components["schemas"]["GameAssets"];
            status: components["schemas"]["CoreStatus"];
            apiStatus: components["schemas"]["CoreApiStatus"];
        };
        GameAssets: {
            /** Format: uri */
            iconUrl: string;
            /** Format: uri */
            tileUrl: string;
            /** Format: uri */
            coverUrl: string;
        };
        GameVersionsByType: {
            /** Format: int32 */
            type: number;
            versions: string[];
        };
        GameVersionsByTypeV2: {
            /** Format: int32 */
            type: number;
            versions: components["schemas"]["GameVersion"][];
        };
        GameVersion: {
            /** Format: int32 */
            id: number;
            name: string;
            slug: string;
        };
        /**
         * @description Possible enum values:
         *      * 1 = Approved
         *      * 2 = Deleted
         *      * 3 = New
         * @enum {integer}
         */
        GameVersionStatus: GameVersionStatus;
        GameVersionType: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            gameId: number;
            name: string;
            slug: string;
            isSyncable: boolean;
            status: components["schemas"]["GameVersionTypeStatus"];
        };
        /**
         * @description Possible enum values:
         *      * 1 = Normal
         *      * 2 = Deleted
         * @enum {integer}
         */
        GameVersionTypeStatus: GameVersionTypeStatus;
        GetCategoriesResponse: {
            /** @description The response data */
            data: components["schemas"]["Category"][];
        };
        GetFeaturedModsResponse: {
            data: components["schemas"]["FeaturedModsResponse"];
        };
        GetFilesResponse: {
            data: components["schemas"]["File"][];
        };
        GetFingerprintMatchesResponse: {
            data: components["schemas"]["FingerprintMatchesResult"];
        };
        GetFingerprintFuzzyMatchesResponse: {
            data: components["schemas"]["FingerprintFuzzyMatchResult"];
        };
        GetGameResponse: {
            data: components["schemas"]["Game"];
        };
        GetGamesResponse: {
            /** @description The response data */
            data: components["schemas"]["Game"][];
            pagination: components["schemas"]["Pagination"];
        };
        GetModFileChangelogResponse: {
            data: string;
        };
        GetModFileDownloadURLResponse: {
            data: string;
        };
        GetModFileResponse: {
            data: components["schemas"]["File"];
        };
        GetModFilesResponse: {
            /** @description The response data */
            data: components["schemas"]["File"][];
            pagination: components["schemas"]["Pagination"];
        };
        GetModResponse: {
            data: components["schemas"]["Mod"];
        };
        GetModsResponse: {
            data: components["schemas"]["Mod"][];
        };
        GetVersionTypesResponse: {
            /** @description The response data */
            data: components["schemas"]["GameVersionType"][];
        };
        GetVersionsResponse: {
            /** @description The response data */
            data: components["schemas"]["GameVersionsByType"][];
        };
        GetVersionsV2Response: {
            /** @description The response data */
            data: components["schemas"]["GameVersionsByTypeV2"][];
        };
        GetFeaturedModsRequestBody: {
            /** Format: int32 */
            gameId: number;
            excludedModIds: number[];
            /** Format: int32 */
            gameVersionTypeId: number | null;
        };
        GetFingerprintMatchesRequestBody: {
            /** @description list of murmur2 hashes with seed 1 */
            fingerprints: number[];
        };
        GetFuzzyMatchesRequestBody: {
            /** Format: int32 */
            gameId: number;
            fingerprints: components["schemas"]["FolderFingerprint"][];
        };
        GetModFilesRequestBody: {
            fileIds: number[];
        };
        GetModsByIdsListRequestBody: {
            modIds: number[];
        };
        /**
         * @description Hash algorithems
         *     Possible enum values:
         *      * 1 = Sha1
         *      * 2 = Md5
         * @enum {integer}
         */
        HashAlgo: HashAlgo;
        MinecraftGameVersion: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            gameVersionId: number;
            versionString: string;
            /** Format: uri */
            jarDownloadUrl: string;
            /** Format: uri */
            jsonDownloadUrl: string;
            approved: boolean;
            /** Format: date-time */
            dateModified: string;
            /** Format: int32 */
            gameVersionTypeId: number;
            gameVersionStatus: components["schemas"]["GameVersionStatus"];
            gameVersionTypeStatus: components["schemas"]["GameVersionTypeStatus"];
        };
        MinecraftModLoaderIndex: {
            name: string;
            gameVersion: string;
            latest: boolean;
            recommended: boolean;
            /** Format: date-time */
            dateModified: string;
            type: components["schemas"]["ModLoaderType"];
        };
        MinecraftModLoaderVersion: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            gameVersionId: number;
            /** Format: int32 */
            minecraftGameVersionId: number;
            forgeVersion: string;
            name: string;
            type: components["schemas"]["ModLoaderType"];
            /** Format: uri */
            downloadUrl: string;
            filename: string;
            installMethod: components["schemas"]["ModLoaderInstallMethod"];
            latest: boolean;
            recommended: boolean;
            approved: boolean;
            /** Format: date-time */
            dateModified: string;
            mavenVersionString: string;
            versionJson: string;
            librariesInstallLocation: string;
            minecraftVersion: string;
            additionalFilesJson: string;
            /** Format: int32 */
            modLoaderGameVersionId: number;
            /** Format: int32 */
            modLoaderGameVersionTypeId: number;
            modLoaderGameVersionStatus: components["schemas"]["GameVersionStatus"];
            modLoaderGameVersionTypeStatus: components["schemas"]["GameVersionTypeStatus"];
            /** Format: int32 */
            mcGameVersionId: number;
            /** Format: int32 */
            mcGameVersionTypeId: number;
            mcGameVersionStatus: components["schemas"]["GameVersionStatus"];
            mcGameVersionTypeStatus: components["schemas"]["GameVersionTypeStatus"];
            installProfileJson: string;
        };
        Mod: {
            /**
             * Format: int64
             * @description The mod id
             */
            id: number;
            /**
             * Format: int64
             * @description The game id this mod is for
             */
            gameId: number;
            /** @description The name of the mod */
            name: string;
            /** @description The mod slug that would appear in the URL */
            slug: string;
            links: components["schemas"]["ModLinks"];
            /** @description Mod summary */
            summary: string;
            status: components["schemas"]["ModStatus"];
            /**
             * Format: int64
             * @description Number of downloads for the mod
             */
            downloadCount: number;
            /**
             * Format: boolean
             * @description Whether the mod is included in the featured mods list
             */
            isFeatured: unknown;
            /**
             * Format: int32
             * @description The main category of the mod as it was chosen by the mod author
             */
            primaryCategoryId: number;
            /** @description List of categories that this mod is related to */
            categories: components["schemas"]["Category"][];
            /**
             * Format: int32
             * @description The class id this mod belongs to
             */
            classId: number | null;
            /** @description List of the mod's authors */
            authors: components["schemas"]["ModAuthor"][];
            logo: components["schemas"]["ModAsset"];
            /** @description List of screenshots assets */
            screenshots: components["schemas"]["ModAsset"][];
            videos: components["schemas"]["ModAsset"][];
            /**
             * Format: int32
             * @description The id of the main file of the mod
             */
            mainFileId: number;
            /** @description List of latest files of the mod */
            latestFiles: components["schemas"]["File"][];
            /** @description List of file related details for the latest files of the mod */
            latestFilesIndexes: components["schemas"]["FileIndex"][];
            /** @description List of file related details for the latest early access files of the mod */
            latestEarlyAccessFilesIndexes: components["schemas"]["FileIndex"][];
            /**
             * Format: date-time
             * @description The creation date of the mod
             */
            dateCreated: string;
            /**
             * Format: date-time
             * @description The last time the mod was modified
             */
            dateModified: string;
            /**
             * Format: date-time
             * @description The release date of the mod
             */
            dateReleased: string;
            /** @description Is mod allowed to be distributed */
            allowModDistribution: boolean | null;
            /**
             * Format: int32
             * @description The mod popularity rank for the game
             */
            gamePopularityRank: number;
            /** @description Is the mod available for search. This can be false when a mod is experimental, in a deleted state or has only alpha files */
            isAvailable: boolean;
            /**
             * Format: int32
             * @description The mod's thumbs up count
             */
            thumbsUpCount: number;
            /** @description Does the mod enable comments */
            hasCommentsEnabled: boolean | null;
            ratingDetails: components["schemas"]["RatingDetails"];
            serverAffiliation: components["schemas"]["ServerAffiliation"];
            /** @description The mod's social links */
            socialLinks: components["schemas"]["SocialLink"][];
        };
        ModAsset: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            modId: number;
            title: string;
            description: string;
            /** Format: uri */
            thumbnailUrl: string;
            /** Format: uri */
            url: string;
        };
        ModAuthor: {
            /** Format: int32 */
            id: number;
            name: string;
            /** Format: uri */
            url: string;
            /** Format: uri */
            avatarUrl: string;
        };
        ModDescriptionResponse: {
            /** @description The response data */
            data: string;
        };
        /** @description Relevant links for the mod such as Issue tracker and Wiki */
        ModLinks: {
            /** Format: uri */
            websiteUrl: string;
            /** Format: uri */
            wikiUrl: string;
            /** Format: uri */
            issuesUrl: string;
            /** Format: uri */
            sourceUrl: string;
        };
        /**
         * @description ModLoaderInstallMethod
         *     Possible enum values:
         *      * 1 = ForgeInstaller
         *      * 2 = ForgeJarInstall
         *      * 3 = ForgeInstaller_v2
         *      * 4 = FabricInstaller
         * @enum {integer}
         */
        ModLoaderInstallMethod: ModLoaderInstallMethod;
        /**
         * @description ModLoaderType
         *     Possible enum values:
         *      * 0 = Any
         *      * 1 = Forge
         *      * 2 = Cauldron
         *      * 3 = LiteLoader
         *      * 4 = Fabric
         *      * 5 = Quilt
         *      * 6 = NeoForge
         * @enum {integer}
         */
        ModLoaderType: ModLoaderType;
        /**
         * @description Possible enum values:
         *      * 1 = Featured
         *      * 2 = Popularity
         *      * 3 = LastUpdated
         *      * 4 = Name
         *      * 5 = Author
         *      * 6 = TotalDownloads
         *      * 7 = Category
         *      * 8 = GameVersion
         *      * 9 = Early Access
         *      * 10 = Featured Release
         *      * 11 = Release Date
         *      * 12 = Rating
         * @enum {integer}
         */
        ModSearchSortField: ModSearchSortField;
        /**
         * @description Current mod status
         *     Possible enum values:
         *      * 1 = New
         *      * 2 = ChangesRequired
         *      * 3 = UnderSoftReview
         *      * 4 = Approved
         *      * 5 = Rejected
         *      * 6 = ChangesMade
         *      * 7 = Inactive
         *      * 8 = Abandoned
         *      * 9 = Deleted
         *      * 10 = UnderReview
         * @enum {integer}
         */
        ModStatus: ModStatus;
        /** @description The response pagination information */
        Pagination: {
            /**
             * Format: int32
             * @description A zero based index of the first item that is included in the response
             */
            index: number;
            /**
             * Format: int32
             * @description The requested number of items to be included in the response
             */
            pageSize: number;
            /**
             * Format: int32
             * @description The actual number of items that were included in the response
             */
            resultCount: number;
            /**
             * Format: int64
             * @description The total number of items available by the request
             */
            totalCount: number;
        };
        /**
         * @description * 0 = Empty
         *     * 1 = Windows
         *     * 2 = XboxOne
         *     * 3 = XboxXS
         *     * 4 = Linux
         *     * 5 = PS4
         *     * 6 = PS5
         *     * 7 = Mac
         *     * 8 = IOS
         *     * 9 = TVOS
         *     * 10 = Android
         *     * 11 = Switch
         *     * 12 = WindowsServer
         *     * 13 = LinuxServer
         * @enum {integer}
         */
        PlatformType: PlatformType;
        /**
         * @description * 0 = All
         *     * 1 = Premium
         *     * 2 = Free
         * @enum {integer}
         */
        PremiumType: PremiumType;
        RatingDetails: {
            /** Format: decimal */
            rating: number | null;
            /** Format: int32 */
            totalRatings: number | null;
            /** Format: int32 */
            positiveRatings: number | null;
            score: components["schemas"]["RatingScore"];
        };
        /**
         * @description * 0 = NotEnoughReviews
         *     * 1 = OverwhelminglyPositive
         *     * 2 = VeryPositive
         *     * 3 = Positive
         *     * 4 = MostlyPositive
         *     * 5 = Mixed
         *     * 6 = MostlyNegative
         *     * 7 = Negative
         *     * 8 = VeryNegative
         *     * 9 = OverwhelminglyNegative
         * @enum {integer}
         */
        RatingScore: RatingScore;
        SearchModsResponse: {
            /** @description The response data */
            data: components["schemas"]["Mod"][];
            pagination: components["schemas"]["Pagination"];
        };
        ServerAffiliation: {
            /** @description Whether the server affiliate program is enabled for this mod */
            isEnabled: boolean;
            isDefaultBanner: boolean;
            hasDiscount: boolean;
            affiliationService: components["schemas"]["AffiliationServiceType"];
            defaultBannerCustomTitle: string;
            /** Format: uri */
            customImageUrl: string;
            /** Format: uri */
            affiliationLink: string;
        };
        SocialLink: {
            type: components["schemas"]["SocialLinkType"];
            /** Format: uri */
            url: string;
        };
        /**
         * @description * 1 = Mastodon
         *     * 2 = Discord
         *     * 3 = Website
         *     * 4 = Facebook
         *     * 5 = Twitter
         *     * 6 = Instagram
         *     * 7 = Patreon
         *     * 8 = Twitch
         *     * 9 = Reddit
         *     * 10 = Youtube
         *     * 11 = TikTok
         *     * 12 = Pinterest
         *     * 13 = Github
         *     * 14 = Bluesky
         * @enum {integer}
         */
        SocialLinkType: SocialLinkType;
        SortableGameVersion: {
            /** @description Original version name (e.g. 1.5b) */
            gameVersionName: string;
            /** @description Used for sorting (e.g. 0000000001.0000000005) */
            gameVersionPadded: string;
            /** @description game version clean name (e.g. 1.5) */
            gameVersion: string;
            /**
             * Format: date-time
             * @description Game version release date
             */
            gameVersionReleaseDate: string;
            /**
             * Format: int32
             * @description Game version type id
             */
            gameVersionTypeId: number | null;
        };
        /**
         * @description Possible enum values:
         *      * asc = Ascending
         *      * desc = Descending
         * @enum {string}
         */
        SortOrder: SortOrder;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    getGames: {
        parameters: {
            query?: {
                /** @description A zero based index of the first item to include in the response, the limit is: (index + pageSize <= 10,000). */
                index?: number;
                /** @description The number of items to include in the response, the default/maximum value is 50. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetGamesResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A game unique id */
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetGameResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A game unique id */
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetVersionsResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVersionsV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A game unique id */
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetVersionsV2Response"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVersionTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A game unique id */
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetVersionTypesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCategories: {
        parameters: {
            query: {
                /** @description A game unique id */
                gameId: number;
                /** @description A class unique id */
                classId?: number;
                /** @description A flag used with gameId to return only classes */
                classesOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCategoriesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchMods: {
        parameters: {
            query: {
                /** @description Filter by game id. */
                gameId: number;
                /** @description A zero based index of the first item to include in the response, the limit is: (index + pageSize <= 10,000). */
                index?: number;
                /** @description The number of items to include in the response, the default/maximum value is 50. */
                pageSize?: number;
                /** @description Filter by section id (discoverable via Categories) */
                classId?: number;
                /** @description Filter by category id */
                categoryId?: number;
                /** @description Filter by game version string */
                gameVersion?: string;
                /** @description Filter by free text search in the mod name and author */
                searchFilter?: string;
                /** @description Filter by ModsSearchSortField enumeration */
                sortField?: components["schemas"]["ModSearchSortField"];
                /** @description 'asc' if sort is in ascending order, 'desc' if sort is in descending order */
                sortOrder?: components["schemas"]["SortOrder"];
                /** @description Filter only mods associated to a given modloader (Forge, Fabric ...). Must be coupled with gameVersion. */
                modLoaderType?: components["schemas"]["ModLoaderType"];
                /** @description Filter only mods that contain files tagged with versions of the given gameVersionTypeId */
                gameVersionTypeId?: number;
                /** @description Filter only mods that the given authorId is a member of. */
                authorId?: number;
                /** @description Filter by slug (coupled with classId will result in a unique result). */
                slug?: string;
                /** @description Filter by a list of category ids. this will override categoryId. Limited to 10 items. */
                categoryIds?: string;
                /** @description Filter by a list of game version strings. This will override gameVersion. Limited to 4 items. */
                gameVersions?: string;
                /** @description Filter by a list of modloader types. This will override modLoaderType. Limited to 5 items. */
                modLoaderTypes?: string;
                /** @description Filter only mods that the given primaryAuthorId is the owner of. */
                primaryAuthorId?: number;
                /** @description Filter only mods that are Premium or not. */
                PremiumType?: components["schemas"]["PremiumType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchModsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mod id. */
                modId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetModResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetModsByIdsListRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetModsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFeaturedMods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetFeaturedModsRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetFeaturedModsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getModDescription: {
        parameters: {
            query?: {
                /** @description Get raw description without things like external link redirects */
                raw?: boolean;
                /** @description Get the description with all HTML tags removed */
                stripped?: boolean;
                markup?: boolean;
            };
            header?: never;
            path: {
                /** @description The mod id. */
                modId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModDescriptionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getModFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mod id the file belongs to */
                modId: number;
                /** @description The file id. */
                fileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetModFileResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getModFiles: {
        parameters: {
            query?: {
                /** @description A zero based index of the first item to include in the response, the limit is: (index + pageSize <= 10,000). */
                index?: number;
                /** @description The number of items to include in the response, the default/maximum value is 50. */
                pageSize?: number;
                /** @description Filter by game version string */
                gameVersion?: string;
                /** @description ModLoaderType enumeration Filter only files associated to a given modloader (Forge, Fabric ...). */
                modLoaderType?: components["schemas"]["ModLoaderType"];
                /** @description Filter only files that are tagged with versions of the given gameVersionTypeId */
                gameVersionTypeId?: number;
                /** @description Filter only files older than the given file ID */
                olderThanProjectFileId?: number;
                /** @description Filter only files that are of the given release types */
                releaseTypes?: components["schemas"]["FileReleaseType"][];
                /** @description Filter only files supporting the given platform type */
                platformType?: components["schemas"]["PlatformType"];
            };
            header?: never;
            path: {
                /** @description The mod id the files belong to */
                modId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetModFilesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetModFilesRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetFilesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getModFileChangelog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mod id the file belongs to */
                modId: number;
                /** @description The file id. */
                fileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetModFileChangelogResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getModFileDownloadURL: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mod id the file belongs to */
                modId: number;
                /** @description The file id. */
                fileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetModFileDownloadURLResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFingerprintMatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body containing an array of fingerprints */
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetFingerprintMatchesRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetFingerprintMatchesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFingerprintMatchesByGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The game id the find matches in */
                gameId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetFingerprintMatchesRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetFingerprintMatchesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFingerprintFuzzyMatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetFuzzyMatchesRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetFingerprintFuzzyMatchesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFingerprintFuzzyMatchesByGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The game id the find matches in */
                gameId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetFuzzyMatchesRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetFingerprintFuzzyMatchesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMinecraftVersions: {
        parameters: {
            query?: {
                sortDescending?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfListOfMinecraftGameVersion"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSpecificMinecraftVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameVersionString: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfMinecraftGameVersion"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMinecraftModLoaders: {
        parameters: {
            query?: {
                version?: string;
                includeAll?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfListOfMinecraftModLoaderIndex"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSpecificMinecraftModLoader: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modLoaderName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfMinecraftModLoaderVersion"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
export enum AffiliationServiceType {
    None = 0,
    Bisect = 1,
    BisectTwo = 2
}
export enum CoreApiStatus {
    Private = 1,
    Public = 2
}
export enum CoreStatus {
    Draft = 1,
    Test = 2,
    PendingReview = 3,
    Rejected = 4,
    Approved = 5,
    Live = 6
}
export enum FileRelationType {
    EmbeddedLibrary = 1,
    OptionalDependency = 2,
    RequiredDependency = 3,
    Tool = 4,
    Incompatible = 5,
    Include = 6
}
export enum FileReleaseType {
    Release = 1,
    Beta = 2,
    Alpha = 3
}
export enum FileStatus {
    Processing = 1,
    ChangesRequired = 2,
    UnderReview = 3,
    Approved = 4,
    Rejected = 5,
    MalwareDetected = 6,
    Deleted = 7,
    Archived = 8,
    Testing = 9,
    Released = 10,
    ReadyForReview = 11,
    Deprecated = 12,
    Baking = 13,
    AwaitingPublishing = 14,
    FailedPublishing = 15,
    Cooking = 16,
    Cooked = 17,
    UnderManualReview = 18,
    ScanningForMalware = 19,
    ProcessingFile = 20,
    PendingRelease = 21,
    ReadyForCooking = 22,
    PostProcessing = 23
}
export enum GameVersionStatus {
    Approved = 1,
    Deleted = 2,
    New = 3
}
export enum GameVersionTypeStatus {
    Normal = 1,
    Deleted = 2
}
export enum HashAlgo {
    Sha1 = 1,
    Md5 = 2
}
export enum ModLoaderInstallMethod {
    ForgeInstaller = 1,
    ForgeJarInstall = 2,
    ForgeInstaller_v2 = 3,
    FabricInstaller = 4
}
export enum ModLoaderType {
    Any = 0,
    Forge = 1,
    Cauldron = 2,
    LiteLoader = 3,
    Fabric = 4,
    Quilt = 5,
    NeoForge = 6
}
export enum ModSearchSortField {
    Featured = 1,
    Popularity = 2,
    LastUpdated = 3,
    Name = 4,
    Author = 5,
    TotalDownloads = 6,
    Category = 7,
    GameVersion = 8,
    Early_Access = 9,
    Featured_Release = 10,
    Release_Date = 11,
    Rating = 12
}
export enum ModStatus {
    New = 1,
    ChangesRequired = 2,
    UnderSoftReview = 3,
    Approved = 4,
    Rejected = 5,
    ChangesMade = 6,
    Inactive = 7,
    Abandoned = 8,
    Deleted = 9,
    UnderReview = 10
}
export enum PlatformType {
    Empty = 0,
    Windows = 1,
    XboxOne = 2,
    XboxXS = 3,
    Linux = 4,
    PS4 = 5,
    PS5 = 6,
    Mac = 7,
    IOS = 8,
    TVOS = 9,
    Android = 10,
    Switch = 11,
    WindowsServer = 12,
    LinuxServer = 13
}
export enum PremiumType {
    All = 0,
    Premium = 1,
    Free = 2
}
export enum RatingScore {
    NotEnoughReviews = 0,
    OverwhelminglyPositive = 1,
    VeryPositive = 2,
    Positive = 3,
    MostlyPositive = 4,
    Mixed = 5,
    MostlyNegative = 6,
    Negative = 7,
    VeryNegative = 8,
    OverwhelminglyNegative = 9
}
export enum SocialLinkType {
    Mastodon = 1,
    Discord = 2,
    Website = 3,
    Facebook = 4,
    Twitter = 5,
    Instagram = 6,
    Patreon = 7,
    Twitch = 8,
    Reddit = 9,
    Youtube = 10,
    TikTok = 11,
    Pinterest = 12,
    Github = 13,
    Bluesky = 14
}
export enum SortOrder {
    Ascending = "asc",
    Descending = "desc"
}
